name: angular_dart_example
version: 0.0.1
dependencies:
  angular:
    path: ../
  browser: any
  unittest: any

transformers:
- angular:
    dart_entry: web/todo.dart
    html_files: web/todo.html

dependency_overrides:
  di:
    git: https://github.com/angular/di.dart.git
